import assert from "node:assert/strict";
import fs from "node:fs";

const cloud = fs.readFileSync(new URL("../js/cloud-sync.js", import.meta.url), "utf8");
const rules = fs.readFileSync(new URL("../firestore.rules", import.meta.url), "utf8");
const manifest = JSON.parse(fs.readFileSync(new URL("../manifest.webmanifest", import.meta.url), "utf8"));
const serviceWorker = fs.readFileSync(new URL("../sw.js", import.meta.url), "utf8");
const html = fs.readFileSync(new URL("../index.html", import.meta.url), "utf8");

for (const collection of [
  "tasks",
  "checklistItems",
  "taskLinks",
  "templates",
  "linkedRules",
  "manualBlocks",
  "owners",
  "categories",
  "holidays",
  "settings",
  "meta",
  "generatedKeys",
  "changeLogs",
]) {
  assert.match(cloud, new RegExp(`\\b${collection}\\b`), `${collection} 컬렉션 계약이 있어야 합니다.`);
}

assert.match(cloud, /runTransaction\(/, "문서 충돌 처리를 위한 Firestore 트랜잭션을 사용해야 합니다.");
assert.doesNotMatch(cloud, /\bgetDocs\b/, "초기 데이터와 실시간 listener를 같은 세션에서 중복 조회하면 안 됩니다.");
assert.match(cloud, /if \(coreReadyPromise\) return coreReadyPromise;/, "핵심 listener 초기화는 세션에서 한 번만 실행해야 합니다.");
assert.match(cloud, /for \(const name of DATA_COLLECTIONS\)[\s\S]*onSnapshot\(collection\(db, name\)/, "핵심 컬렉션의 최초 listener 스냅샷을 초기 데이터로 재사용해야 합니다.");
assert.match(cloud, /cachedOffline[\s\S]*navigator\.onLine === false/, "오프라인에서는 준비된 Firestore 캐시로 앱을 열 수 있어야 합니다.");
assert.match(cloud, /!initialLoad\.serverConfirmed[\s\S]*기존 클라우드 데이터는 변경되지 않습니다/, "빈 오프라인 캐시를 새 클라우드로 오인하면 안 됩니다.");
assert.match(cloud, /function loadChangeLogs\(\)[\s\S]*limit\(CHANGE_LOG_LIMIT\)/, "변경이력은 화면에서 요청할 때만 제한 조회해야 합니다.");
assert.match(html, /historyPage[\s\S]*loadChangeLogs/, "변경이력 화면 진입이 지연 listener를 시작해야 합니다.");
assert.match(html, /async function exportJson\(\)\{await window\.cloudSync\?\.loadChangeLogs/, "JSON 백업은 지연된 변경이력까지 준비한 뒤 내려받아야 합니다.");
assert.match(cloud, /writeChanges\.filter\(\(item\) => item\.type === "update"\)/, "생성·삭제 문서를 트랜잭션에서 의미 없이 선조회하면 안 됩니다.");
assert.match(cloud, /makeLog\(appliedWriteChanges, metadata\)/, "동시 생성 잠금으로 건너뛴 작업은 변경로그를 쓰면 안 됩니다.");
assert.match(cloud, /JSON\.stringify\(remote\[field\]\) !== JSON\.stringify\(change\.after\[field\]\)/, "트랜잭션 시점에 원격 값이 이미 같으면 update를 생략해야 합니다.");
assert.match(cloud, /persistentLocalCache/, "Firestore 영속 오프라인 캐시를 켜야 합니다.");
assert.match(cloud, /persistentMultipleTabManager/, "여러 탭이 같은 오프라인 캐시를 안전하게 공유해야 합니다.");
assert.match(cloud, /https:\/\/www\.googleapis\.com\/auth\/drive\.file/, "Drive 권한은 앱이 만든/연 파일로 제한해야 합니다.");
assert.doesNotMatch(cloud, /auth\/drive(?:["'])/, "전체 Google Drive 권한을 요청하면 안 됩니다.");
assert.match(cloud, /hasDriveAccess\(\)/, "사진 선택 전에 Drive 권한 준비 여부를 확인할 수 있어야 합니다.");
assert.match(cloud, /DRIVE_TOKEN_SESSION_KEY/, "Drive 접근 토큰은 같은 탭에서 다시 사용할 수 있어야 합니다.");
assert.match(cloud, /sessionStorage\.setItem\(DRIVE_TOKEN_SESSION_KEY/, "Drive 접근 토큰은 영구 저장소가 아닌 세션에만 보관해야 합니다.");
assert.match(cloud, /createFileBlock/, "업무 DB 양식 파일을 Drive에 업로드할 수 있어야 합니다.");
assert.match(cloud, /downloadDriveFile/, "Drive 첨부파일을 앱에서 내려받을 수 있어야 합니다.");
assert.match(cloud, /MAX_DRIVE_FILE_BYTES/, "브라우저 업로드에 안전한 파일 크기 제한이 있어야 합니다.");
assert.match(cloud, /popup-blocked/, "팝업 차단 오류를 사용자가 해결할 수 있는 안내로 변환해야 합니다.");
assert.doesNotMatch(cloud, /signInWithRedirect/, "iPad 저장공간 제한을 유발하는 리디렉션 로그인을 사용하면 안 됩니다.");
assert.doesNotMatch(cloud, /getRedirectResult/, "사용하지 않는 리디렉션 로그인 결과를 확인하면 안 됩니다.");
assert.match(cloud, /browserSessionPersistence/, "로컬 인증 저장소를 사용할 수 없을 때 세션 저장소로 대체해야 합니다.");
assert.match(cloud, /inMemoryPersistence/, "브라우저 저장소가 모두 제한되면 메모리 인증으로 대체해야 합니다.");
assert.match(cloud, /generatedKeys/, "생성 키 잠금 컬렉션이 있어야 합니다.");
assert.match(cloud, /snap\.exists\(\)[\s\S]*skippedTaskIds\.add\(lockChange\.after\.taskId\)/, "동시 생성 잠금이 이미 있으면 같은 안정적 ID도 다시 쓰지 않아야 합니다.");
assert.match(html, /autoGeneratedThrough/, "반복 원본별 Rolling 마지막 확보 범위를 기록해야 합니다.");
assert.match(html, /appendMissingTemplateOccurrencesV24/, "자동 연장 시 없는 미래 회차만 추가해야 합니다.");
assert.match(html, /ROLLING_AUTO_MONTHS_V24=12/, "자동 확보 범위는 Rolling 12개월이어야 합니다.");
assert.match(html, /rollingTemplateSessionTokenV24/, "같은 세션에서 동일한 Rolling 범위를 반복 검사하지 않아야 합니다.");
assert.match(html, /ensureDbLinkedChildrenV5\(root,template,'append'\)/, "부분 저장 실패 뒤에도 기존 단계는 보존하고 누락 연계단계만 복구해야 합니다.");
assert.match(cloud, /changeLogs/, "문서 단위 변경이력 컬렉션이 있어야 합니다.");
assert.match(cloud, /id="cloudOwnerUid"/, "최초 로그인에서 소유자 UID를 확인할 수 있어야 합니다.");
assert.match(cloud, /UID는 비밀번호나 인증코드가 아닌 계정 식별값입니다/, "UID 안내가 비밀정보와 구분되어야 합니다.");

assert.match(rules, /function isOwner\(\)/, "소유자 검사 함수가 있어야 합니다.");
assert.match(rules, /request\.auth\.uid == '(?:__OWNER_UID__|[A-Za-z0-9_-]+)'/, "Firebase UID로 소유자를 제한해야 합니다.");
assert.match(rules, /match \/\{document=\*\*\}\s*\{\s*allow read, write: if false;/s, "기본 거부 규칙이 있어야 합니다.");
assert.match(rules, /match \/generatedKeys\/\{(?:docId|id)\}/, "중복 방지 잠금 규칙이 있어야 합니다.");
assert.match(rules, /request\.resource\.data\.generatedKey == resource\.data\.generatedKey/, "생성 키 값이 같은 멱등 재전송만 허용해야 합니다.");
assert.match(rules, /request\.resource\.data\.taskId == resource\.data\.taskId/, "생성 키가 다른 업무로 바뀌면 안 됩니다.");
assert.match(rules, /allow delete: if false;/, "생성 키 잠금은 삭제할 수 없어야 합니다.");
assert.match(rules, /match \/changeLogs\/\{id\}[\s\S]*allow update, delete: if false;/, "변경이력은 수정·삭제할 수 없어야 합니다.");

assert.equal(manifest.display, "standalone", "PWA는 standalone 모드로 열려야 합니다.");
assert.ok(Array.isArray(manifest.icons) && manifest.icons.some((icon) => icon.sizes === "192x192"), "192px PWA 아이콘이 있어야 합니다.");
assert.ok(manifest.icons.some((icon) => icon.sizes === "512x512"), "512px PWA 아이콘이 있어야 합니다.");
assert.match(serviceWorker, /self\.addEventListener\("fetch"/, "서비스 워커가 오프라인 요청을 처리해야 합니다.");
for (const moduleName of ["firebase-app.js", "firebase-auth.js", "firebase-firestore.js"]) {
  assert.match(serviceWorker, new RegExp(moduleName.replace(".", "\\.")), `${moduleName}을 첫 설치 때 미리 캐시해야 합니다.`);
}
assert.match(serviceWorker, /cache\.addAll\(FIREBASE_MODULES\)\.catch/, "Firebase CDN 장애가 앱 셸 설치를 막으면 안 됩니다.");
assert.match(serviceWorker, /work-manager-v10-shell-2026-09-13-31/, "6단계 업무DB 점검 배포 캐시 버전이어야 합니다.");

console.log("PASS cloud/PWA contract: Drive session and file attachment included");
