import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";

const html = fs.readFileSync(new URL("../index.html", import.meta.url), "utf8");
const cloud = fs.readFileSync(new URL("../js/cloud-sync.js", import.meta.url), "utf8");
const serviceWorker = fs.readFileSync(new URL("../sw.js", import.meta.url), "utf8");

for (const [index, match] of [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].entries()) {
  new vm.Script(match[1], { filename: `index-inline-${index + 1}.js` });
}

function extractLastFunction(name) {
  const matcher = new RegExp(`(?:async\\s+)?function\\s+${name}\\s*\\(`, "g");
  let found = null;
  for (let match; (match = matcher.exec(html));) found = match.index;
  assert.notEqual(found, null, `${name} 함수가 있어야 합니다.`);
  const argsOpen = html.indexOf("(", found);
  let argsDepth = 0;
  let argsClose = -1;
  for (let index = argsOpen; index < html.length; index += 1) {
    if (html[index] === "(") argsDepth += 1;
    else if (html[index] === ")" && --argsDepth === 0) { argsClose = index; break; }
  }
  const open = html.indexOf("{", argsClose);
  let depth = 0;
  let quote = "";
  let escaped = false;
  for (let index = open; index < html.length; index += 1) {
    const char = html[index];
    if (quote) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === quote) quote = "";
      continue;
    }
    if (char === "'" || char === '"' || char === "`") quote = char;
    else if (char === "{") depth += 1;
    else if (char === "}" && --depth === 0) return html.slice(found, index + 1);
  }
  throw new Error(`${name} 함수의 끝을 찾지 못했습니다.`);
}

let sequence = 0;
let uploadCalls = 0;
const sandbox = {
  Date, String, Number, Array, Object, Map, Set, Math, JSON,
  TEMPLATE_ATTACHMENT_EXTENSIONS_V30: new Set(["hwp", "hwpx", "xls", "xlsx", "pdf", "doc", "docx", "ppt", "pptx", "csv", "txt"]),
  TEMPLATE_CLONE_OMIT_FIELDS_V30: ["id", "autoGeneratedThrough", "generatedKey", "seriesId", "groupId", "parentAutoRootId", "parentSeriesId", "autoSourceTemplateId", "dbSourceTemplateId", "dbManualRootTemplateId", "actualComplete", "status", "revision", "createdAt", "updatedAt", "deletedAt", "archivedSourceDeleted", "archivedSourceDeletedAt", "archivedSourceTrashId", "changeLogs", "history", "versions", "templateVersionV29"],
  archiveCloneV29(value) {
    if (value == null) return value;
    return JSON.parse(JSON.stringify(value, (key, item) => ["data", "objectUrl", "blobUrl", "previewUrl"].includes(key) ? undefined : item));
  },
  uid(prefix) { sequence += 1; return `${prefix}-new-${sequence}`; },
  async makeMethodFileBlock(file, id) {
    uploadCalls += 1;
    return { id, type: "file", driveFileId: "drive-uploaded", name: file.name, mimeType: file.type, size: file.size, caption: "" };
  },
};
const context = vm.createContext(sandbox);
for (const name of [
  "templateAttachmentExtensionV30",
  "cleanTemplateAttachmentV30",
  "cloneMethodBlocksV30",
  "templateCloneDraftV30",
  "makeTemplateAttachmentV30",
  "openDbCloneV30",
]) vm.runInContext(extractLastFunction(name), context);

const uploaded = await context.makeTemplateAttachmentV30({ name: "점검 결과.PDF", type: "application/pdf", size: 1234 });
assert.equal(uploadCalls, 1, "지원 문서는 기존 Drive 업로드 헬퍼를 한 번만 호출해야 합니다.");
assert.equal(uploaded.driveFileId, "drive-uploaded", "Firestore에는 Drive 연결 ID를 남겨야 합니다.");
assert.equal(uploaded.name, "점검 결과.PDF", "원래 파일명을 메타데이터로 유지해야 합니다.");
assert.equal(uploaded.size, 1234, "파일 크기는 메타데이터로만 유지해야 합니다.");
await assert.rejects(context.makeTemplateAttachmentV30({ name: "danger.exe", type: "application/octet-stream", size: 20 }), /HWP/, "실행파일은 관련 자료로 허용하면 안 됩니다.");
assert.equal(uploadCalls, 1, "지원하지 않는 파일은 Drive 호출 전에 차단해야 합니다.");

const source = {
  id: "tpl-source",
  name: "소방 점검",
  category: "소방",
  owner: "담당자",
  cycle: "monthly",
  exactDay: 4,
  activeFrom: "2026-01-01",
  activeUntil: "",
  autoSchedule: true,
  autoGeneratedThrough: "2027-09-30",
  checklist: ["보고서 확인"],
  methodBlocks: [{ id: "mb-old", type: "image", driveFileId: "drive-image", data: "blob:temporary", objectUrl: "blob:temporary" }],
  attachments: [{ id: "att-old", type: "file", driveFileId: "drive-form", name: "결과보고서.hwp", mimeType: "application/x-hwp", size: 500, data: "forbidden-bytes" }],
  linkedSteps: [
    { id: "rule-old", rootTemplateId: "tpl-source", templateId: "tpl-source", name: "결과 제출", checklist: ["제출"], methodBlocks: [{ id: "step-mb-old", type: "image", driveFileId: "drive-step-image" }] },
    { templateId: "tpl-reference", name: "후속 확인", methodBlocks: [] },
  ],
  revision: 7,
};
const sourceBefore = JSON.stringify(source);
const draft = context.templateCloneDraftV30(source);
assert.equal(JSON.stringify(source), sourceBefore, "복제 초안을 만들 때 원본 업무DB를 변경하면 안 됩니다.");
assert.equal("id" in draft, false, "복제 초안은 원본 업무DB ID를 가져가면 안 됩니다.");
assert.equal("autoGeneratedThrough" in draft, false, "원본 Rolling 확보표시는 복제하면 안 됩니다.");
assert.equal("revision" in draft, false, "원본 Firestore revision은 복제하면 안 됩니다.");
assert.equal(draft.name, "소방 점검 - 복사본", "사용자가 복제본을 인식할 수 있는 편집 가능한 이름을 채워야 합니다.");
assert.equal(draft.category, "소방", "대분류를 복제해야 합니다.");
assert.equal(draft.owner, "담당자", "담당자를 복제해야 합니다.");
assert.equal(draft.cycle, "monthly", "반복설정을 복제해야 합니다.");
assert.deepEqual(Array.from(draft.checklist), ["보고서 확인"], "체크리스트 정의를 복제해야 합니다.");
assert.notEqual(draft.methodBlocks[0].id, "mb-old", "manualBlock 구조 ID는 새로 만들어야 합니다.");
assert.equal(draft.methodBlocks[0].driveFileId, "drive-image", "manualBlock Drive 이미지는 물리 복사 없이 같은 파일을 참조해야 합니다.");
assert.equal("data" in draft.methodBlocks[0], false, "복제 초안에 파일 bytes/object URL을 포함하면 안 됩니다.");
assert.notEqual(draft.attachments[0].id, "att-old", "첨부 연결 ID는 새로 만들어야 합니다.");
assert.equal(draft.attachments[0].driveFileId, "drive-form", "첨부자료는 Drive 복사 없이 같은 driveFileId를 사용해야 합니다.");
assert.equal("data" in draft.attachments[0], false, "첨부자료 메타데이터에 파일 bytes를 넣으면 안 됩니다.");
assert.equal("id" in draft.linkedSteps[0], false, "연계규칙 원본 ID를 복제하면 안 됩니다.");
assert.equal("rootTemplateId" in draft.linkedSteps[0], false, "연계규칙이 원본 부모 업무DB를 계속 참조하면 안 됩니다.");
assert.equal("templateId" in draft.linkedSteps[0], false, "원본 자신을 참조하는 연계 templateId는 제거해야 합니다.");
assert.equal(draft.linkedSteps[1].templateId, "tpl-reference", "다른 업무DB를 명시적으로 참조한 연계설정은 유지해야 합니다.");
assert.notEqual(draft.linkedSteps[0].methodBlocks[0].id, "step-mb-old", "연계 manualBlock ID도 새로 만들어야 합니다.");
assert.equal(draft.linkedSteps[0].methodBlocks[0].driveFileId, "drive-step-image", "연계 manualBlock 이미지는 같은 Drive 파일을 참조해야 합니다.");

const cloneEntry = extractLastFunction("openDbCloneV30");
assert.match(cloneEntry, /openDbForm\(null,templateCloneDraftV30\(source\)\)/, "복제 버튼은 저장 대신 새 작성폼에 초안을 전달해야 합니다.");
assert.doesNotMatch(cloneEntry, /saveState|syncTemplateSchedule|createFileBlock|fetch/, "복제 버튼 자체는 Firestore, Rolling, Drive 호출을 하면 안 됩니다.");
assert.match(html, /function openDbForm\(id=null,seed=null\)[\s\S]*clone\(orig\|\|seed\|\|/, "기존 작성폼이 복제 초안을 받아야 합니다.");
assert.match(html, /else\{t\.id=uid\('tpl'\);state\.templates\.push\(t\)\}/, "최종 저장 때만 새 업무DB ID를 만들어야 합니다.");
assert.match(html, /복제 초안입니다\. 아직 Firestore나 수행업무에 저장되지 않았습니다/, "복제 작성폼에 미저장 상태를 안내해야 합니다.");
assert.match(html, /id="cloneDbV30">업무DB 복제<\/button>/, "업무DB 상세·수정 화면에 복제 진입점이 있어야 합니다.");

assert.match(html, /<legend>관련 양식 \/ 자료<\/legend>/, "업무DB 작성폼에 별도 관련 자료 영역이 있어야 합니다.");
for (const extension of ["hwp", "hwpx", "xls", "xlsx", "pdf", "doc", "docx", "ppt", "pptx", "csv", "txt"]) {
  assert.match(html, new RegExp(`['\"]${extension}['\"]`), `${extension.toUpperCase()} 파일을 지원해야 합니다.`);
}
assert.match(html, /data-template-attachment-remove-v30[\s\S]*attachments\.splice/, "연결 제거는 메타데이터 배열에서만 제거해야 합니다.");
assert.match(cloud, /async function openDriveFile[\s\S]*previewable[\s\S]*downloadDriveFile/, "미리보기 가능한 파일은 열고 나머지는 기존 다운로드 방식을 사용해야 합니다.");
assert.match(cloud, /createDriveBlock\(file, \{ id, type: "file", kind: "template-attachment" \}\)/, "관련 자료는 기존 Drive 업로드 구조를 사용해야 합니다.");
assert.match(cloud, /const \{ checklist = \[\], linkedSteps = \[\], methodBlocks = \[\], attachments = \[\], photos, method, \.\.\.templateFields \} = template;[\s\S]*attachments: attachments\.map\(cleanAttachmentMetadata\)/, "첨부 메타데이터는 별도 전체조회 없이 업무DB 문서에 포함되어야 합니다.");
assert.match(cloud, /function cleanAttachmentMetadata[\s\S]*"data"[\s\S]*"objectUrl"/, "직접 가져온 데이터에도 파일 bytes나 임시 URL이 Firestore로 들어가면 안 됩니다.");
const collectionDeclaration = cloud.slice(cloud.indexOf("const DATA_COLLECTIONS"), cloud.indexOf("const LIVE_COLLECTIONS"));
assert.doesNotMatch(collectionDeclaration, /attachments/, "첨부자료 전용 collection/listener를 추가하면 안 됩니다.");
const appV30 = html.slice(html.lastIndexOf("APP V30 — template attachments / clone draft"));
assert.doesNotMatch(appV30, /onSnapshot|getDocs|setDoc|updateDoc|runTransaction|collection\s*\(/, "8단계 UI에 새 Firestore read/listener를 추가하면 안 됩니다.");
assert.match(html, /\{label:'첨부자료',value:\(source\?\.attachments\|\|\[\]\)\.map/, "현재 로드된 업무DB 첨부파일명을 통합검색에 포함해야 합니다.");

const archived = sandbox.archiveCloneV29(source);
assert.equal(archived.attachments[0].driveFileId, "drive-form", "휴지통·버전 snapshot에는 첨부 연결정보를 보존해야 합니다.");
assert.equal("data" in archived.attachments[0], false, "휴지통·버전 snapshot에는 파일 bytes를 복제하면 안 됩니다.");
assert.match(html, /versionSummaryV29=function\(snapshot\)[\s\S]*snapshot\.attachments/, "버전 화면에서 첨부 연결 개수를 확인할 수 있어야 합니다.");
assert.match(serviceWorker, /work-manager-v10-shell-2026-09-13-33/, "8단계 서비스워커 캐시를 사용해야 합니다.");

console.log("PASS stage 8 template attachments and clone draft regression");
